apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment-healthcheck
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-deployment-healthcheck
    spec:
      containers:
      - name: k8s-demo
        image: gnoguchi/node-hello-world-k8s-test
        ports:
        - name: nodejs-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30 